/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteAdminRouteImport } from './routes/site-admin'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SiteAdminSiteEditorRouteImport } from './routes/site-admin/site-editor'
import { Route as SiteAdminMonitoringRouteImport } from './routes/site-admin/monitoring'
import { Route as AdminResidentsRouteImport } from './routes/admin/residents'
import { Route as AdminFinanceRouteImport } from './routes/admin/finance'
import { Route as AdminDocumentsRouteImport } from './routes/admin/documents'
import { Route as AdminBlotterRouteImport } from './routes/admin/blotter'

const SiteAdminRoute = SiteAdminRouteImport.update({
  id: '/site-admin',
  path: '/site-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SiteAdminSiteEditorRoute = SiteAdminSiteEditorRouteImport.update({
  id: '/site-editor',
  path: '/site-editor',
  getParentRoute: () => SiteAdminRoute,
} as any)
const SiteAdminMonitoringRoute = SiteAdminMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => SiteAdminRoute,
} as any)
const AdminResidentsRoute = AdminResidentsRouteImport.update({
  id: '/residents',
  path: '/residents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlotterRoute = AdminBlotterRouteImport.update({
  id: '/blotter',
  path: '/blotter',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/services': typeof ServicesRoute
  '/site-admin': typeof SiteAdminRouteWithChildren
  '/admin/blotter': typeof AdminBlotterRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/residents': typeof AdminResidentsRoute
  '/site-admin/monitoring': typeof SiteAdminMonitoringRoute
  '/site-admin/site-editor': typeof SiteAdminSiteEditorRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/announcements': typeof AnnouncementsRoute
  '/services': typeof ServicesRoute
  '/site-admin': typeof SiteAdminRouteWithChildren
  '/admin/blotter': typeof AdminBlotterRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/residents': typeof AdminResidentsRoute
  '/site-admin/monitoring': typeof SiteAdminMonitoringRoute
  '/site-admin/site-editor': typeof SiteAdminSiteEditorRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/services': typeof ServicesRoute
  '/site-admin': typeof SiteAdminRouteWithChildren
  '/admin/blotter': typeof AdminBlotterRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/residents': typeof AdminResidentsRoute
  '/site-admin/monitoring': typeof SiteAdminMonitoringRoute
  '/site-admin/site-editor': typeof SiteAdminSiteEditorRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/about'
    | '/admin'
    | '/announcements'
    | '/services'
    | '/site-admin'
    | '/admin/blotter'
    | '/admin/documents'
    | '/admin/finance'
    | '/admin/residents'
    | '/site-admin/monitoring'
    | '/site-admin/site-editor'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/about'
    | '/announcements'
    | '/services'
    | '/site-admin'
    | '/admin/blotter'
    | '/admin/documents'
    | '/admin/finance'
    | '/admin/residents'
    | '/site-admin/monitoring'
    | '/site-admin/site-editor'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/about'
    | '/admin'
    | '/announcements'
    | '/services'
    | '/site-admin'
    | '/admin/blotter'
    | '/admin/documents'
    | '/admin/finance'
    | '/admin/residents'
    | '/site-admin/monitoring'
    | '/site-admin/site-editor'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnnouncementsRoute: typeof AnnouncementsRoute
  ServicesRoute: typeof ServicesRoute
  SiteAdminRoute: typeof SiteAdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/site-admin': {
      id: '/site-admin'
      path: '/site-admin'
      fullPath: '/site-admin'
      preLoaderRoute: typeof SiteAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/site-admin/site-editor': {
      id: '/site-admin/site-editor'
      path: '/site-editor'
      fullPath: '/site-admin/site-editor'
      preLoaderRoute: typeof SiteAdminSiteEditorRouteImport
      parentRoute: typeof SiteAdminRoute
    }
    '/site-admin/monitoring': {
      id: '/site-admin/monitoring'
      path: '/monitoring'
      fullPath: '/site-admin/monitoring'
      preLoaderRoute: typeof SiteAdminMonitoringRouteImport
      parentRoute: typeof SiteAdminRoute
    }
    '/admin/residents': {
      id: '/admin/residents'
      path: '/residents'
      fullPath: '/admin/residents'
      preLoaderRoute: typeof AdminResidentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blotter': {
      id: '/admin/blotter'
      path: '/blotter'
      fullPath: '/admin/blotter'
      preLoaderRoute: typeof AdminBlotterRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBlotterRoute: typeof AdminBlotterRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminResidentsRoute: typeof AdminResidentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlotterRoute: AdminBlotterRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminResidentsRoute: AdminResidentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SiteAdminRouteChildren {
  SiteAdminMonitoringRoute: typeof SiteAdminMonitoringRoute
  SiteAdminSiteEditorRoute: typeof SiteAdminSiteEditorRoute
}

const SiteAdminRouteChildren: SiteAdminRouteChildren = {
  SiteAdminMonitoringRoute: SiteAdminMonitoringRoute,
  SiteAdminSiteEditorRoute: SiteAdminSiteEditorRoute,
}

const SiteAdminRouteWithChildren = SiteAdminRoute._addFileChildren(
  SiteAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AnnouncementsRoute: AnnouncementsRoute,
  ServicesRoute: ServicesRoute,
  SiteAdminRoute: SiteAdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
